<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>lua</string>
	</array>
	<key>name</key>
	<string>Lua Dev</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#general</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>arrayindex</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>meta.arrayindex.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
			</array>
		</dict>
		<key>blockcomment</key>
		<dict>
			<key>begin</key>
			<string>--\[(=*)\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]\1\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.lua</string>
		</dict>
		<key>constant</key>
		<dict>
			<key>match</key>
			<string>nil|true|false|_G|_VERSION|\.\.\.</string>
			<key>name</key>
			<string>constant.language.lua</string>
		</dict>
		<key>doublequotestring</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.lua</string>
				</dict>
			</array>
		</dict>
		<key>forblock</key>
		<dict>
			<key>begin</key>
			<string>\bfor\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\bend\b</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.forblock.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
			</array>
		</dict>
		<key>function</key>
		<dict>
			<key>begin</key>
			<string>\b(function)(\s+(((\w(\w|\d)*)(\.|:))*(\w(\w|\d)*)))?\s*(\()\s*((\.\.\.|\w(\w|\d)*)(,\s*(\.\.\.|\w(\w|\d)*))*)?\s*(\))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.lua</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.lua</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>end</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
			</array>
		</dict>
		<key>functioncall</key>
		<dict>
			<key>begin</key>
			<string>((\w(\w|\d)*[\.:])*\w(\w|\d)*)\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.functioncall.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
			</array>
		</dict>
		<key>general</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#linecomment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#blockcomment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#singlequotestring</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doublequotestring</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#multilinestring</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functioncall</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#if</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ifblock</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#forblock</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#whileblock</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#repeatblock</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tabledecl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arrayindex</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
			</array>
		</dict>
		<key>ifblock</key>
		<dict>
			<key>begin</key>
			<string>\bif\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\bend\b</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.ifblock.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>match</key>
			<string>\b(break|do|else|for|if|elseif|return|then|repeat|while|until|end|function|local|in)\b</string>
			<key>name</key>
			<string>keyword.control.lua</string>
		</dict>
		<key>libfunctioncall</key>
		<dict>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(assert|collectgarbage|dofile|error|getfenv|getmetatable|ipairs|loadfile|loadstring|module|next|pairs|pcall|print|rawequal|rawget|rawset|require|select|setfenv|setmetatable|tonumber|tostring|type|unpack|xpcall|coroutine\.(create|resume|running|status|wrap|yield)|string\.(byte|char|dump|find|format|gmatch|gsub|len|lower|match|rep|reverse|sub|upper)|table\.(concat|insert|maxn|remove|sort)|math\.(abs|acos|asin|atan2?|ceil|cosh?|deg|exp|floor|fmod|frexp|ldexp|log|log10|max|min|modf|pow|rad|random|randomseed|sinh?|sqrt|tanh?)|io\.(close|flush|input|lines|open|output|popen|read|tmpfile|type|write)|os\.(clock|date|difftime|execute|exit|getenv|remove|rename|setlocale|time|tmpname)|package\.(cpath|loaded|loadlib|path|preload|seeall)|debug\.(debug|[gs]etfenv|[gs]ethook|getinfo|[gs]etlocal|[gs]etmetatable|getregistry|[gs]etupvalue|traceback))\b(?=[( {])</string>
			<key>name</key>
			<string>meta.functioncall.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
			</array>
		</dict>
		<key>linecomment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.lua</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(--)(?!(\[=*\[|\]=*\])).*$
?</string>
			<key>name</key>
			<string>comment.line.double-dash.lua</string>
		</dict>
		<key>multilinestring</key>
		<dict>
			<key>begin</key>
			<string>\[(=*)\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]\1\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.block.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.lua</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>(?&lt;![\d.])\s0x[a-fA-F\d]+|\b\d+(\.\d+)?([eE]-?\d+)?|\.\d+([eE]-?\d+)?</string>
			<key>name</key>
			<string>constant.numeric.lua</string>
		</dict>
		<key>operator</key>
		<dict>
			<key>match</key>
			<string>(\b(and|or|not)\b)|(\+|-|%|#|\*|\/|\^|==?|~=|&lt;=?|&gt;=?|(?&lt;!\.)\.{2}(?!\.))</string>
			<key>name</key>
			<string>keyword.operator.lua</string>
		</dict>
		<key>repeatblock</key>
		<dict>
			<key>begin</key>
			<string>\brepeat\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\buntil\b</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.repeatblock.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
			</array>
		</dict>
		<key>singlequotestring</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.lua</string>
				</dict>
			</array>
		</dict>
		<key>tabledecl</key>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>meta.tabledecl.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>match</key>
			<string>([A-Za-z_][A-Za-z0-9_\.]*)</string>
			<key>name</key>
			<string>variable.other.lua</string>
		</dict>
		<key>whileblock</key>
		<dict>
			<key>begin</key>
			<string>\bwhile\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\bend\b</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.whileblock.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.lua</string>
	<key>uuid</key>
	<string>d3691eb0-1e00-4893-90fc-1a78c6c100b0</string>
</dict>
</plist>
